#!/usr/bin/python3
# -*- coding: utf-8 -*-

import json
# import matplotlib.pyplot as plt
import os
import shared

with open(os.path.join("..", "testset_full", "metadata.json")) as f:
  metadata = json.load(f)

structures = shared.get_structure_dict()

for pdb in metadata:
  # mtz_resolution = metadata[pdb]["resolution"]
  # pdb_resolution = structures[pdb.upper()].resolution
  # diff = abs(mtz_resolution - pdb_resolution)
  # if diff > 0.2:
  #   print("| %s | %4.2f | %4.2f | %4.2f |" % (pdb, pdb_resolution, mtz_resolution, diff))

  rfree = metadata[pdb]["reference_rfree"]
  if rfree > 0.4:
    print("| %s | %4.2f |" % (pdb, rfree))

# x = [metadata[pdb]["resolution"] for pdb in sorted(metadata.keys())]
# y = [metadata[pdb]["reference_rfree"] for pdb in sorted(metadata.keys())]

# fig = plt.figure(figsize=(8.85 / 2.54, 7 / 2.54))
# ax1 = fig.add_subplot(111)

# ax1.plot(x, y, color=colour1, marker="o", linewidth=0, alpha=0.7, markersize=4)
# ax1.set_xlabel(u"Resolution / Å")
# ax1.set_ylabel("Reference R-free")
# ax1.tick_params(direction="out", length=3, pad=3, top=False, right=False)

# plt.tight_layout(pad=0.3, rect=(0, 0.05, 1, 1))
# plt.show()
