#!/usr/bin/python3

from Bio import SeqIO
import os
import shutil
import uuid

class Hit:
  def __init__(self, pdb, chain, qscore, rmsd, seqid):
    self.pdb = pdb
    self.chain = chain
    self.qscore = qscore
    self.rmsd = rmsd
    self.seqid = seqid
    self.cluster = None
    if pdb.upper() in structures:
      for chain in structures[pdb.upper()].chains:
        if chain.id == self.chain:
          attr = "cluster%d" % args.diff_seqid
          self.cluster = getattr(chain, attr)
          break

def unique_chains():
  path = os.path.join(args.pdb, "protein.fasta")
  for record in SeqIO.parse(path, "fasta"):
    yield record.id.split(",")[0]

def possible_gesamt_hits(chain):
  hits_path = os.path.join(args.pdb, "chain%s_gesamt.txt" % chain)
  with open(hits_path) as hits_file:
    for line in hits_file:
      if line[0] == "#": continue
      split = line.split()
      hit_pdb = split[1].lower()
      hit_chain = split[2]
      qscore = float(split[3])
      rmsd = float(split[4])
      seqid = float(split[5])
      if qscore > args.min_qscore and rmsd < args.max_rmsd and seqid < (args.diff_seqid / 100.0):
        yield Hit(hit_pdb, hit_chain, qscore, rmsd, seqid)

def alignment_stats(hit1, hit2):
  tmp_prefix = "tmp%s" % uuid.uuid4()
  path1 = os.path.join(args.pdbs, hit1.pdb[1:3], "pdb%s.ent.gz" % hit1.pdb)
  path2 = os.path.join(args.pdbs, hit2.pdb[1:3], "pdb%s.ent.gz" % hit2.pdb)
  tasks.superpose(path1, hit1.chain, path2, hit2.chain, tmp_prefix)
  os.remove(tmp_path) # TODO: Remove all files starting with this prefix
  return stats

def should_choose(hit, chosen_hits):
  if hit.cluster is None: return False
  for chosen_hit in reversed(chosen_hits):
    if hit.cluster == chosen_hit.cluster: return False
  for chosen_hit in reversed(chosen_hits):
    stats = alignment_stats(hit, chosen_hit)
    if stats["rmsd"] is not None and stats["rmsd"] < args.diff_rmsd: return False
    if stats["seqid"] is not None and stats["seqid"] > (args.diff_seqid / 100.0): return False
  return True

def reset_models_directory():
  path = os.path.join(args.pdb, "models")
  if os.path.exists(path): shutil.rmtree(path)
  os.mkdir(path)

if __name__ == "__main__":
  args = parse_args()
  structures = shared.get_structure_dict()
  reset_models_directory()
  for chain in unique_chains():
    print("## Choosing hits for %s:%s" % (args.pdb, chain))
    chosen_hits = []
    for hit in possible_gesamt_hits(chain):
      if should_choose(hit, chosen_hits):
        print(hit.__dict__)
        chosen_hits.append(hit)
        os.mkdir(os.path.join(args.pdb, "models", "%s_%s%s" % (chain, hit.pdb, hit.chain)))
        if len(chosen_hits) == args.max_models:
          break
