#!/usr/bin/python3

from Bio import SeqIO
import collections
import os
import shared
import uuid

Hit = collections.namedtuple("Hit", ["pdb", "chain"])

def unique_chains(pdb):
  path = os.path.join(pdb, "protein.fasta")
  for record in SeqIO.parse(path, "fasta"):
    yield record.id.split(",")[0]

def gesamt_hits(pdb, chain):
  reference_pdb = os.path.join(pdb, "reference.pdb")
  hits_path = os.path.join(pdb, "chain%s_gesamt.txt" % chain)
  if not os.path.exists(hits_path):
    shared.run("gesamt", [
      reference_pdb, "-s", chain,
      "-archive", "/data/gesamt/archive",
      "-nthreads=auto",
      "-o", hits_path,
    ])
  with open(hits_path) as hits_file:
    for line in hits_file:
      if line[0] == "#": continue
      split = line.split()
      qscore = float(split[3])
      rmsd = float(split[4])
      seqid = float(split[5])
      if qscore > 0.1 and rmsd < 2 and seqid < 0.95:
        yield Hit(split[1].lower(), split[2])

def aligned_identity(hit1, hit2):
  tmp_path = "tmp%s" % uuid.uuid4()
  path1 = "/data/pdb/pdb/%s/pdb%s.ent.gz" % (hit1.pdb[1:3], hit1.pdb)
  path2 = "/data/pdb/pdb/%s/pdb%s.ent.gz" % (hit2.pdb[1:3], hit2.pdb)
  shared.run("gesamt", [
    path1, "-s", hit1.chain,
    path2, "-s", hit2.chain,
  ], stdout=tmp_path)
  with open(tmp_path) as gesamt_log:
    lines = gesamt_log.readlines()
  for line in lines:
    if line[:19] == " Sequence Id:     :":
      os.remove(tmp_path)
      return float(line[19:])

def similar_to_already_chosen(hit, chosen_hits):
  for chosen_hit in reversed(chosen_hits):
    if aligned_identity(hit, chosen_hit) >= 0.95:
      return True
  return False

def mkdir(path):
  try: os.mkdir(path)
  except: pass

if __name__ == "__main__":
  pdbs = [line.strip() for line in open("refine_passed")]
  for pdb in pdbs:
    mkdir(os.path.join(pdb, "models"))
    for chain in unique_chains(pdb):
      chosen_hits = []
      for hit in gesamt_hits(pdb, chain):
        if not similar_to_already_chosen(hit, chosen_hits):
          chosen_hits.append(hit)
          mkdir(os.path.join(pdb, "models", "%s_%s%s" % (chain, hit.pdb, hit.chain)))
