#!/usr/bin/env ccp4-python

import os
import re

def no_models(pdb):
  models = os.listdir(os.path.join(pdb, "models"))
  return len(models) == 0

pdbs = [line.strip() for line in open("refine_passed")]
with open("choose_models_failed", "w") as failed, open("choose_models_passed", "w") as passed:
  for pdb in pdbs:
    if no_models(pdb):
      failed.write("%s Has no models\n" % pdb)
    else:
      passed.write("%s\n" % pdb)
