#!/usr/bin/python3

tasks.superpose(target_gz(), args.chain, model_gz(), args.model_chain, os.path.join(args.dir, "gesamt"))
tasks.post_process_gesamt_alignment(
  alnin=gesamt_fasta(),
  alnout=sculptor_fasta(),
  id1="%s%s" % (args.pdb, args.chain),
  id2="%s%s" % (args.model_pdb, args.model_chain),
)
tasks.trim_model(model_gz(), args.model_chain, sculptor_fasta(), os.path.join(args.dir, "sculptor"))
tasks.mr(joined_mtz(), sculptor_pdb(), identity(), os.path.join(args.dir, "phaser"), n_copies(), pdbtools.count_elements())
tasks.refine(joined_mtz, phaser_pdb, os.path.join(args.dir, "refmac"))
tasks.combine_mtz(cmtzjoin_mtz(), [
  (joined_mtz(), "FP,SIGFP", "FP,SIGFP"),
  (joined_mtz(), "FREE", "FREE"),
  (joined_mtz(), "reference.HLA,reference.HLB,reference.HLC,reference.HLD", "reference.HLA,reference.HLB,reference.HLC,reference.HLD"),
  (refmac_mtz(), "HLACOMB,HLBCOMB,HLCCOMB,HLDCOMB", "model.HLA,model.HLB,model.HLC,model.HLD"),
])
tasks.compare_phases(cmtzjoin_mtz(), "FP,SIGFP", "model.HLA,model.HLB,model.HLC,model.HLD", "reference.HLA,reference.HLB,reference.HLC,reference.HLD")
