#!/usr/bin/env ccp4-python

import argparse
import clipper
import json
import os
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET

def parse_args():
  parser = argparse.ArgumentParser(description="Refines a single structure using data deposited in the PDB.")
  parser.add_argument("id", help="PDB ID for the structure")
  parser.add_argument("pdb", help="PDB format coordinate file (gzipped)")
  parser.add_argument("sf", help="CIF format reflection data file (gzipped)")
  parser.add_argument("seq", help="FASTA format sequence file")
  return parser.parse_args()

def run(executable, args=[], stdin=[], stdout=None):
  pstdin = subprocess.PIPE if len(stdin) > 0 else None
  pstdout = None if stdout is None else open(stdout, "w")
  command = [executable] + args
  p = subprocess.Popen(command, stdin=pstdin, stdout=pstdout)
  if pstdin == subprocess.PIPE:
    for line in stdin:
      p.stdin.write(line + "\n")
    p.stdin.close()
  p.wait()

def cad_mtz(): return "%s/cad.mtz" % args.id
def cif2mtz_mtz(): return "%s/cif2mtz.mtz" % args.id
def cphasematch_txt(): return "%s/cphasematch.txt" % args.id
def ctruncate_mtz(): return "%s/ctruncate.mtz" % args.id
def deposited_cif(): return "%s/%s-sf.cif" % (args.id, args.id)
def deposited_pdb(): return "%s/%s.pdb" % (args.id, args.id)
def freerflag_mtz(): return "%s/freerflag.mtz" % args.id
def joined_mtz(): return "%s/joined.mtz" % args.id
def metadata_json(): return "%s/metadata.json" % args.id
def no_symm_cif(): return "%s/no_symm.cif" % args.id
def no_unl_pdb(): return "%s/no_unl.pdb" % args.id
def reference_mmcif(): return "%s/reference.mmcif" % args.id
def reference_mtz(): return "%s/reference.mtz" % args.id
def reference_pdb(): return "%s/reference.pdb" % args.id
def reference_xml(): return "%s/reference.xml" % args.id

def check_input():
  if not os.path.exists(args.pdb):
    sys.exit("Can't find input file: %s" % args.pdb)
  if not os.path.exists(args.sf):
    sys.exit("Can't find input file: %s" % args.sf)
  if not os.path.exists(args.seq):
    sys.exit("Can't find input file: %s" % args.seq)

def unzip_input():
  run("gunzip", ["-c", args.pdb], stdout=deposited_pdb())
  run("gunzip", ["-c", args.sf], stdout=deposited_cif())

def remove_symmetry_number():
  shutil.copy(deposited_cif(), no_symm_cif())
  run("sed", ["-i", "/^_symmetry.Int_Tables_number/d", no_symm_cif()])

def convert_to_mtz():
  run("cif2mtz", [
    "hklin", no_symm_cif(),
    "hklout", cif2mtz_mtz(),
  ], ["END"])

def ctruncate(columns):
  arguments = [
    "-hklin", cif2mtz_mtz(),
    "-hklout", ctruncate_mtz(),
    "-seqin", args.seq,
  ]
  if len(columns) == 2:
    arguments.extend(["-colin", "/*/*/[%s]" % ",".join(columns)])
  else:
    arguments.extend(["-colano", "/*/*/[%s]" % ",".join(columns)])
  if columns[0][0] == "F":
    arguments.append("-amplitudes")
  run("ctruncate", arguments)

def add_freeflag():
  run("freerflag", [
    "hklin", ctruncate_mtz(),
    "hklout", freerflag_mtz()
  ], ["END"])

def rename_column_labels(f, sigf):
  run("cad", [
    "hklin1", freerflag_mtz(),
    "hklout", cad_mtz()
  ], [
    "LABI FILE_NUMBER 1 E1=FreeR_flag E2=%s E3=%s" % (f, sigf),
    "XNAME FILE_NUMBER 1 ALL=",
    "DNAME FILE_NUMBER 1 ALL=",
    "LABO FILE_NUMBER 1 E1=FREE E2=FP E3=SIGFP",
    "END",
  ])

def standardise_mtz():
  f = clipper.CCP4MTZfile()
  f.open_read(cif2mtz_mtz())
  labels = [str(l).split()[0].split("/")[-1] for l in f.column_labels()]
  anomalous = False
  if all(l in labels for l in ["FP", "SIGFP"]):
    ctruncate(["FP", "SIGFP"])
  elif all(l in labels for l in ["I", "SIGI"]):
    ctruncate(["I", "SIGI"])
  elif all(l in labels for l in ["F(+)", "SIGF(+)", "F(-)", "SIGF(-)"]):
    ctruncate(["F(+)", "SIGF(+)", "F(-)", "SIGF(-)"])
    anomalous = True
  elif all(l in labels for l in ["I(+)", "SIGI(+)", "I(-)", "SIGI(-)"]):
    ctruncate(["I(+)", "SIGI(+)", "I(-)", "SIGI(-)"])
    anomalous = True
  else:
    sys.exit("Can't find columns to convert to F,SIGF: [%s]" % " ".join(labels))
  add_freeflag()
  if anomalous: rename_column_labels("FMEAN", "SIGFMEAN")
  else: rename_column_labels("F", "SIGF")

def remove_unl_residues():
  shutil.copy(deposited_pdb(), no_unl_pdb())
  run("sed", ["-i", "/^HET.*UNL/d", no_unl_pdb()])
  run("sed", ["-i", "/^ATOM.*UNL/d", no_unl_pdb()])
  run("sed", ["-i", "/^REMARK 500.*UNL/d", no_unl_pdb()])

def refine_reference():
  run("refmac5", [
    "xyzin", no_unl_pdb(),
    "hklin", cad_mtz(),
    "xyzout", reference_pdb(),
    "hklout", reference_mtz(),
    "xmlout", reference_xml(),
  ], [
    "PHOUT"
    "END"
  ])

def join_mtz_files():
  run("cmtzjoin", [
    "-mtzout", joined_mtz(),
    "-mtzin", cad_mtz(),
    "-colin", "FP,SIGFP",
    "-colout", "FP,SIGFP",
    "-mtzin", cad_mtz(),
    "-colin", "FREE",
    "-colout", "FREE",
    "-mtzin", reference_mtz(),
    "-colin", "HLACOMB,HLBCOMB,HLCCOMB,HLDCOMB",
    "-colout", "reference.HLA,reference.HLB,reference.HLC,reference.HLD"
  ])

def mtz_metadata():
  f = clipper.CCP4MTZfile()
  f.open_read(joined_mtz())
  return {
    "resolution": round(f.resolution().limit(), 2),
    "spacegroup": f.spacegroup().symbol_hm(),
    "cell": [
      round(f.cell().a(), 2),
      round(f.cell().b(), 2),
      round(f.cell().c(), 2),
      round(clipper.Util_rad2d(f.cell().alpha()), 1),
      round(clipper.Util_rad2d(f.cell().beta()), 1),
      round(clipper.Util_rad2d(f.cell().gamma()), 1),
    ],
  }

def reference_metadata():
  root = ET.parse(reference_xml()).getroot()
  rworks = list(root.iter("r_factor"))
  rfrees = list(root.iter("r_free"))
  return {
    "reference_rwork": float(rworks[-1].text),
    "reference_rfree": float(rfrees[-1].text),
  }

def is_semet():
  with open(reference_pdb()) as f:
    for line in f:
      if line[:6] == "ATOM  " or line[:6] == "HETATM":
        if line[17:20] == "MET": return False
        if line[17:20] == "MSE": return True
  return False

def write_metadata():
  metadata = {
    "pdb_id": args.id,
    "semet": is_semet()
  }
  metadata.update(mtz_metadata())
  metadata.update(reference_metadata())
  json.dump(metadata, open(metadata_json(), "w"), indent=2, sort_keys=True)

if __name__ == "__main__":
  args = parse_args()
  run("mkdir", ["-p", args.id])
  check_input()
  unzip_input()
  remove_symmetry_number()
  convert_to_mtz()
  standardise_mtz()
  remove_unl_residues()
  refine_reference()
  join_mtz_files()
  write_metadata()
