#!/usr/bin/env ccp4-python

import os
import re

def has_needed_files(pdb):
  paths = [
    os.path.join(pdb, "joined.mtz"),
    os.path.join(pdb, "metadata.json"),
    os.path.join(pdb, "reference.pdb"),
  ]
  return all(os.path.exists(p) for p in paths)

def failure_reason(pdb):
  with open("%s.err" % pdb) as f:
    stderr = f.read()
  errors = [
    "Can't find input file",
    "cif2mtz:  No symmetry information in keywords or file!",
    "Can't find columns to convert to F,SIGF",
    "Refmac:  New ligand has been encountered",
    "Refmac:  Problem with coordinate file",
    "Refmac:  Fatal error",
  ]
  for error in errors:
    if error in stderr: return error
  return "Unknown reason"

pdbs = [line.strip() for line in open("chosen_structures")]
with open("refine_failed", "w") as failed, open("refine_passed", "w") as passed:
  for pdb in pdbs:
    if has_needed_files(pdb):
      passed.write("%s\n" % pdb)
    else:
      failed.write("%s %s\n" % (pdb, failure_reason(pdb)))
