#!/usr/bin/env ccp4-python

import os
import shutil

def remove(path):
  try: os.remove(path)
  except: pass

passed = [line.strip() for line in open("refine_passed")]
for pdb in passed:
  remove("%s/cad.mtz" % pdb)
  remove("%s/cif2mtz.mtz" % pdb)
  remove("%s/cphasematch.txt" % pdb)
  remove("%s/ctruncate.mtz" % pdb)
  remove("%s/%s-sf.cif" % (pdb, pdb))
  remove("%s/%s.pdb" % (pdb, pdb))
  remove("%s/freerflag.mtz" % pdb)
  remove("%s/no_symm.cif" % pdb)
  remove("%s/no_unl.pdb" % pdb)
  remove("%s/reference.mmcif" % pdb)
  remove("%s/reference.mtz" % pdb)
  remove("%s/reference.xml" % pdb)
  remove("%s.log" % pdb)
  remove("%s.err" % pdb)

failed = [line.strip() for line in open("refine_failed")]
for pdb in failed:
  shutil.rmtree(pdb)
  remove("%s.log" % pdb)
  remove("%s.err" % pdb)
