#!/usr/bin/env ccp4-python

from Bio import SeqIO
import argparse
import os
import sys

parser = argparse.ArgumentParser(description="Extracts a fasta sequence from the SEQRES section of a PDB file.")
parser.add_argument("xyzin", help="Input coordinate file in PDB format")
parser.add_argument("seqout", help="Output sequence file in FASTA format")
args = parser.parse_args()

if not os.path.exists(args.xyzin):
  sys.exit("Cannot find file: " + args.xyzin)

records = SeqIO.parse(args.xyzin, "pdb-seqres")
SeqIO.write(records, args.seqout, "fasta")
